update(java): disable autobuild; disable server trace; delete -Xbootclasspath jvm-arg, which will cause `java.lang.NoClassDefFoundError: javax/annotation/processing/AbstractProcessor`;